# Generated by Django 6.1.1 on 2026-10-07 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_minutos',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(blank=True, help_text='Escriba horas:minutos:segundos. Ejemplo: 02:30:00', null=True, verbose_name='Duración estimada'),
        ),
        migrations.CreateModel(
            name='TarifaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica_a', models.CharField(choices=[('1-4_KG', '1 a 4 kg'), ('5-10_KG', '5 a 10 kg'), ('11-15_KG', '11 a 15 kg'), ('16-19_KG', '16 a 19 kg'), ('20-25_KG', '20 a 25 kg'), ('26-30_KG', '26 a 30 kg'), ('31-35_KG', '31 a 35 kg'), ('GATOS', 'Gatos'), ('UNICO', 'Precio único')], max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='servicios.servicio')),
            ],
        ),
    ]
