# Generated by Django 6.1.1 on 2026-09-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_servicio_precio_tarifaservicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifaservicio',
            old_name='categoria',
            new_name='aplica_a',
        ),
    ]
