# Generated by Django 6.1.1 on 2026-09-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_rename_categoria_tarifaservicio_aplica_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifaservicio',
            name='aplica_a',
            field=models.CharField(choices=[('1-4_KG', '1 a 4 kg'), ('5-10_KG', '5 a 10 kg'), ('11-15_KG', '11 a 15 kg'), ('16-19_KG', '16 a 19 kg'), ('20-25_KG', '20 a 25 kg'), ('26-30_KG', '26 a 30 kg'), ('31-35_KG', '31 a 35 kg'), ('POMERANIA', 'Pomerania'), ('CHOW_CHOW', 'Chow Chow'), ('GATO', 'Gato'), ('UNICO', 'Precio único')], max_length=100),
        ),
    ]
