# Generated by Django 6.1.1 on 2026-09-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_tarifaservicio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_minutos',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.DurationField(blank=True, help_text='Escriba horas:minutos:segundos. Ejemplo: 02:30:00', null=True, verbose_name='Duración estimada'),
        ),
    ]
